name: CI
on:
  push:
    branches:
      - "**"
jobs:
  check:
    if: github.repository != 'pachun/expo-npm-template'
    runs-on: ubuntu-latest
    outputs:
      version_changed: ${{ steps.version.outputs.version_changed }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - run: yarn
      - run: yarn lint
      - run: yarn build
      - run: yarn test --collectCoverage

      - if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: we-cli/coverage-badge-action@main

      - if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        id: version
        run: |
          git fetch origin main --depth=2
          previous_commit=$(git rev-parse origin/main^1)
          git show $previous_commit:package.json > package.json.previous
          previous_version=$(jq -r '.version' package.json.previous)
          current_version=$(jq -r '.version' package.json)
          if [ "$current_version" != "$previous_version" ]; then
            echo "version_changed=true" >> $GITHUB_OUTPUT
          else
            echo "version_changed=false" >> $GITHUB_OUTPUT
          fi

  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && needs.check.outputs.version_changed == 'true'
    needs: check
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
          # Defaults to the user or organization that owns the workflow file
          scope: "@octocat"
      - run: yarn
      - run: yarn build
      - run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
